Repository RPCS3/discord-bot, pull requests merged in 2019-08, with the labels that each got.

#361 Small fixes
  CompatBot/Commands/Misc.cs
  CompatBot/Database/Providers/ContentFilter.cs
  CompatBot/EventHandlers/LogParsingHandler.cs
Labels: bug, fun stuff

#363 Fix several issues with the autosplit messages
  CompatBot/Commands/Syscall.cs
  CompatBot/Utils/Extensions/AutosplitResponseHelper.cs
Labels: bug

#364 Limit !syscall to spam channel only
  CompatBot/Commands/Syscall.cs
Labels: bug

#365 New log parser notes
  CompatBot/Commands/Syscall.cs
  CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
Labels: log analyzer

#366 Fix posting log parsing results
  CompatBot/Commands/Syscall.cs
  CompatBot/EventHandlers/LogParsingHandler.cs
Labels: bug, log analyzer

#367 !syscall improvements
  CompatBot/Commands/Syscall.cs
Labels: enhancement

#368 Testing in production is great, isn't it
  CompatBot/Commands/Syscall.cs
Labels: bug

#369 Misc updates
  Clients/CompatApiClient/Client.cs
  CompatBot/Commands/BotStats.cs
  CompatBot/Commands/Syscall.cs
  CompatBot/Database/Providers/ContentFilter.cs
  CompatBot/EventHandlers/LogParsing/ArchiveHandlers/GzipHandler.cs
  CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
  CompatBot/EventHandlers/LogParsingHandler.cs
  CompatBot/Utils/Extensions/DiscordClientExtensions.cs
  CompatBot/Utils/ReportSeverity.cs
Labels: enhancement

#370 Improve AMD GPU driver version detection
  CompatBot/Database/Providers/AmdDriverVersionProvider.cs
Labels: log analyzer

#371 Very important fix
  CompatBot/Commands/Misc.cs
  CompatBot/Commands/Syscall.cs
  CompatBot/Utils/Extensions/StringUtils.cs
Labels: bug, fun stuff

#373 Check DeS settings for fps patch
  CompatBot/EventHandlers/LogParsing/SourceHandlers/GenericLinkHandler.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
Labels: log analyzer

#374 Additional log checks
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
Labels: log analyzer

#375 New log checks
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
Labels: log analyzer

#376 Misc fixes
  CompatBot/Commands/Moderation.cs
  CompatBot/Commands/Sudo.Bot.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
Labels: bug, enhancement, log analyzer

#377 New DeS settings checks, and fixed typos
  CompatBot/Commands/Misc.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
Labels: bug, fun stuff, log analyzer

#378 Mark the end of an era
  CompatBot/EventHandlers/Starbucks.cs
Labels: fun stuff

#379 Stream zip and rar logs
  CompatBot/EventHandlers/LogParsing/ArchiveHandlers/RarHandler.cs
  CompatBot/EventHandlers/LogParsing/ArchiveHandlers/ZipHandler.cs
Labels: enhancement, log analyzer

#380 Misc improvements
  CompatBot/Commands/Attributes/CheckBaseAttributeWithReactions.cs
  CompatBot/Commands/EventsBaseCommand.cs
  CompatBot/Commands/Moderation.cs
  CompatBot/Commands/Pr.cs
  CompatBot/Commands/Psn.Check.cs
  CompatBot/Commands/Sudo.cs
  CompatBot/EventHandlers/AppveyorLinksHandler.cs
  CompatBot/EventHandlers/BotReactionsHandler.cs
  CompatBot/EventHandlers/DiscordInviteFilter.cs
  CompatBot/EventHandlers/ProductCodeLookup.cs
  CompatBot/EventHandlers/Starbucks.cs
  CompatBot/Utils/Extensions/DiscordClientExtensions.cs
  CompatBot/Utils/Extensions/InteractivityExtensions.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
  CompatBot/Utils/TimeParser.cs
  Tests/Tests.csproj
  Tests/TimeParserTests.cs
Labels: enhancement

#381 Fix weird install path detection in multi run logs
  CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
Labels: bug, log analyzer

#382 Hope & Despair (Quotes for Rate)
  CompatBot/Commands/Misc.cs
Labels: fun stuff

#383 Fix project compilation
  CompatBot/Commands/Misc.cs
  Tests/TimeParserTests.cs
Labels: bug, high priority

#384 Minor updates
  Clients/AppveyorClient/Client.cs
  CompatBot/CompatBot.csproj
  CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
  CompatBot/Utils/Extensions/RolesExtensions.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
Labels: enhancement, log analyzer

#385 Ability to mark update announcement as a bad update
  CompatBot/Commands/CompatList.cs
  CompatBot/Commands/Moderation.cs
  CompatBot/Config.cs
  CompatBot/EventHandlers/Starbucks.cs
Labels: enhancement

#386 Nerf check for disc dumps inside /dev_hdd0/game/
  CompatBot/EventHandlers/Starbucks.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.CurrentSettingsSections.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
Labels: bug, log analyzer

#387 Add support for online-only flag in compatibility api
  Clients/CompatApiClient/POCOs/CompatResult.cs
  CompatBot/Utils/ResultFormatters/TitleInfoFormatter.cs
Labels: enhancement

#389 Quality of life improvements
  CompatBot/Commands/Sudo.Bot.cs
  CompatBot/Database/Providers/ContentFilter.cs
  CompatBot/EventHandlers/LogParsing/ArchiveHandlers/PlainText.cs
  CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
  CompatBot/EventHandlers/LogParsingHandler.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
  README.md
Labels: enhancement, log analyzer

#390 Code documentation, part deux
  CompatBot/Commands/Attributes/readme.md
  CompatBot/Commands/ContentFilters.cs
  CompatBot/Commands/Converters/readme.md
  CompatBot/Commands/readme.md
  CompatBot/Database/Providers/readme.md
  CompatBot/Database/readme.md
  CompatBot/Program.cs
  README.md
Labels: enhancement

#391 New and updated game checks
  CompatBot/Database/readme.md
  CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
Labels: log analyzer

#392 Misc improvements
  CompatBot/EventHandlers/GithubLinksHandler.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
  CompatBot/Utils/ResultFormatters/UpdateInfoFormatter.cs
Labels: bug, enhancement, log analyzer

#393 Fix detection of corrupted save data
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
Labels: bug, log analyzer

#394 Improve event name matching, add temporary ama command
  CompatBot/Commands/EventsBaseCommand.cs
  CompatBot/Commands/Rpcs3Ama.cs
  CompatBot/Program.cs
Labels: enhancement

#395 Implement check for ps3 firmware update
  Clients/CompatApiClient/Compression/CompressionMessageHandler.cs
  Clients/PsnClient/POCOs/Container.cs
  Clients/PsnClient/PsnClient.cs
  CompatBot/Commands/Misc.cs
  CompatBot/Commands/Psn.Check.cs
  CompatBot/Utils/ResultFormatters/FwInfoFormatter.cs
Labels: enhancement

#396 Changes to "JoJo's Bizarre Adventure: All Star Battle" recommended settings
  CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
Labels: log analyzer

#397 Small bugfixes
  CompatBot/Commands/CompatList.cs
  CompatBot/Database/Providers/ContentFilter.cs
  CompatBot/EventHandlers/DiscordInviteFilter.cs
  CompatBot/EventHandlers/LogParsingHandler.cs
  CompatBot/Utils/ResultFormatters/FwInfoFormatter.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
  Tests/TimeParserTests.cs
Labels: bug, log analyzer

#398 Fix log parsing results formatting
  CompatBot/EventHandlers/LogParsingHandler.cs
  CompatBot/Utils/Extensions/StringUtils.cs
Labels: bug, high priority

#399 Fix another issue with broken formatting
  CompatBot/Commands/CompatList.cs
  CompatBot/Commands/EventsBaseCommand.cs
  CompatBot/Utils/Extensions/StringUtils.cs
  CompatBot/Utils/ResultFormatters/TitleInfoFormatter.cs
Labels: bug

#400 Fix missing license list
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
Labels: bug
