Repository RPCS3/discord-bot, pull requests merged in 2019-01, with the labels that each got.

#146 Use extra information from the new update info model
  CompatApiClient/Client.cs
  CompatApiClient/CompatApiClient.csproj
  CompatBot/Commands/CompatList.cs
  CompatBot/CompatBot.csproj
  CompatBot/Config.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
  CompatBot/Utils/ResultFormatters/UpdateInfoFormatter.cs
  IrdLibraryClient/IrdLibraryClient.csproj
  PsnClient/PsnClient.csproj
  Tests/Tests.csproj
Labels: enhancement

#147 Replace PSN scraping with tmdb api calls
  CompatBot/Database/Providers/ThumbnailProvider.cs
  PsnClient/POCOs/TitleMeta.cs
  PsnClient/PsnClient.cs
  PsnClient/Utils/TmdbHasher.cs
Labels: enhancement

#149 Some small features and fixes
  CompatBot/Commands/BotMath.cs
  CompatBot/Commands/Explain.cs
  CompatBot/Commands/Misc.cs
  CompatBot/Commands/Moderation.cs
  CompatBot/Program.cs
  CompatBot/Utils/CommandContextExtensions.cs
  CompatBot/Utils/DiscordClientExtensions.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
  PsnClient/PsnClient.cs
Labels: enhancement, log analyzer

#150 Workaround bug in command module
  CompatBot/Commands/Explain.cs
Labels: bug

#151 Ability to send greeting message to all new users
  CompatBot/Commands/Explain.cs
  CompatBot/EventHandlers/Greeter.cs
  CompatBot/Program.cs
Labels: enhancement

#152 Hotfix for AF settings detection
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
Labels: bug

#153 Detect /root_host/ shenanigans
  CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
Labels: log analyzer

#155 Fix dice rolls without valid values, but with comments
  CompatBot/Commands/Misc.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
  CompatBot/Utils/ResultFormatters/TitleInfoFormatter.cs
Labels: bug, log analyzer

#156 Implement !pr command
  AppveyorClient/AppveyorClient.csproj
  AppveyorClient/Client.cs
  AppveyorClient/POCOs/Artifact.cs
  AppveyorClient/POCOs/ArtifactInfo.cs
  AppveyorClient/POCOs/Build.cs
  AppveyorClient/POCOs/BuildInfo.cs
  AppveyorClient/POCOs/Job.cs
  AppveyorClient/POCOs/Project.cs
  CompatApiClient/Client.cs
  CompatApiClient/POCOs/PrInfo.cs
  CompatApiClient/Utils/Utils.cs
  CompatBot/Commands/Explain.cs
  CompatBot/Commands/Pr.cs
  CompatBot/CompatBot.csproj
  CompatBot/Config.cs
  CompatBot/EventHandlers/BotShutupHandler.cs
  CompatBot/Program.cs
  CompatBot/Utils/ResultFormatters/PrInfoFormatter.cs
  CompatBot/Utils/ResultFormatters/TitlePatchFormatter.cs
  CompatBot/Utils/ResultFormatters/UpdateInfoFormatter.cs
  CompatBot/Utils/StringUtils.cs
  GithubClient/Client.cs
  GithubClient/GithubClient.csproj
  GithubClient/POCOs/PrInfo.cs
  GithubClient/POCOs/StatusInfo.cs
  discord-bot-net.sln
Labels: enhancement

#157 Make !commands command usable by non-sudoer mods
  CompatBot/Commands/CommandsManagement.cs
  CompatBot/Commands/Sudo.Bot.Commands.cs
  CompatBot/Program.cs
Labels: enhancement

#158 Improvements to !pr command
  AppveyorClient/Client.cs
  AppveyorClient/POCOs/Build.cs
  AppveyorClient/POCOs/BuildInfo.cs
  AppveyorClient/POCOs/HistoryInfo.cs
  CompatBot/Commands/Antipiracy.cs
  CompatBot/Commands/Attributes/TriggersTyping.cs
  CompatBot/Commands/BotMath.cs
  CompatBot/Commands/CommandsManagement.cs
  CompatBot/Commands/CompatList.cs
  CompatBot/Commands/CustomBaseCommand.cs
  CompatBot/Commands/Explain.cs
  CompatBot/Commands/Invites.cs
  CompatBot/Commands/Misc.cs
  CompatBot/Commands/Moderation.Audit.cs
  CompatBot/Commands/Pr.cs
  CompatBot/Commands/Sudo.Bot.cs
  CompatBot/Commands/Sudo.Fix.cs
  CompatBot/Commands/Sudo.Mod.cs
  CompatBot/Commands/Warnings.ListGroup.cs
  CompatBot/Commands/Warnings.cs
  CompatBot/Config.cs
  CompatBot/EventHandlers/LogParsingHandler.cs
  CompatBot/EventHandlers/ProductCodeLookup.cs
  CompatBot/EventHandlers/UsernameSpoofMonitor.cs
  CompatBot/Utils/DiscordClientExtensions.cs
  CompatBot/Utils/ResultFormatters/PrInfoFormatter.cs
  CompatBot/Utils/ResultFormatters/UpdateInfoFormatter.cs
  GithubClient/Client.cs
  GithubClient/POCOs/PrInfo.cs
Labels: bug, enhancement

#159 More improvements to PR linking
  AppveyorClient/Client.cs
  CompatBot/Commands/Misc.cs
  CompatBot/Commands/Pr.cs
  CompatBot/Config.cs
  CompatBot/EventHandlers/GithubLinksHandler.cs
  CompatBot/Program.cs
  CompatBot/Utils/ResultFormatters/UpdateInfoFormatter.cs
  GithubClient/Client.cs
Labels: bug, enhancement

#160 Link latest PR build if someone posts appveyor link
  AppveyorClient/Client.cs
  CompatBot/Commands/Pr.cs
  CompatBot/EventHandlers/AppveyorLinksHandler.cs
  CompatBot/EventHandlers/GithubLinksHandler.cs
  CompatBot/Program.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
Labels: enhancement

#161 prevent accidental issue linking
  CompatBot/EventHandlers/GithubLinksHandler.cs
Labels: bug

#162 Enhancments to github linking
  AppveyorClient/Client.cs
  CompatBot/EventHandlers/AppveyorLinksHandler.cs
  CompatBot/EventHandlers/BotShutupHandler.cs
  CompatBot/EventHandlers/GithubLinksHandler.cs
  CompatBot/EventHandlers/ProductCodeLookup.cs
  CompatBot/Program.cs
Labels: bug, enhancement, fun stuff

#163 Fix PR build linking when it was merged, but not built yet
  AppveyorClient/Client.cs
  CompatBot/Commands/Pr.cs
  CompatBot/EventHandlers/BotShutupHandler.cs
  CompatBot/Program.cs
Labels: bug, fun stuff

#164 Change some wording a bit for better formatting and usability
  CompatBot/EventHandlers/LogParsingHandler.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
  CompatBot/Utils/ResultFormatters/TitleInfoFormatter.cs
Labels: enhancement

#166 Minor quality of life improvements
  CompatBot/Commands/Pr.cs
  CompatBot/EventHandlers/BotShutupHandler.cs
  CompatBot/Utils/DateTimeEx.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
  CompatBot/Utils/ResultFormatters/UpdateInfoFormatter.cs
Labels: bug, enhancement

#167 Small enhancements
  AppveyorClient/Client.cs
  CompatBot/Commands/Pr.cs
  CompatBot/EventHandlers/BotShutupHandler.cs
  CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
  CompatBot/Utils/ResultFormatters/UpdateInfoFormatter.cs
Labels: bug, fun stuff, log analyzer

#169 Hotfix for the new corrupted dumps
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
Labels: bug

#171 More fixes to the log parser
  AppveyorClient/Client.cs
  CompatBot/Commands/Attributes/LimitedToSpamChannel.cs
  CompatBot/Commands/Pr.cs
  CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
Labels: enhancement, log analyzer

#173 Small fixes
  CompatBot/Commands/Explain.cs
  CompatBot/Commands/Pr.cs
  CompatBot/EventHandlers/DiscordInviteFilter.cs
  CompatBot/Utils/ResultFormatters/UpdateInfoFormatter.cs
Labels: bug

#174 !reanalyze command
  CompatBot/Commands/Attributes/RequiresDm.cs
  CompatBot/Commands/Moderation.cs
  CompatBot/EventHandlers/LogParsing/LogParser.PipeReader.cs
  CompatBot/EventHandlers/LogParsing/SourceHandlers/RarHandler.cs
  CompatBot/EventHandlers/LogParsing/SourceHandlers/SevenZipHandler.cs
  CompatBot/EventHandlers/LogParsing/SourceHandlers/ZipHandler.cs
  CompatBot/EventHandlers/LogParsingHandler.cs
  CompatBot/Utils/DiscordClientExtensions.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
Labels: enhancement, log analyzer

#175 More log parsing fixes
  CompatBot/EventHandlers/BotShutupHandler.cs
  CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
  CompatBot/EventHandlers/LogParsing/LogParser.PipeReader.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
Labels: bug, fun stuff, log analyzer

#176 Use PSN DeS product code for compatibility checks
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
Labels: log analyzer

#177 Fix potential issue with piracy reporting, maybe?
  CompatBot/EventHandlers/LogParsingHandler.cs
Labels: bug

#178 Fix the exception that prevents posting log results in some cases
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
Labels: bug

#179 Fix typo
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
Labels: bug

#181 Maintenance update
  CompatBot/Database/Providers/ThumbnailProvider.cs
  CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
  CompatBot/Utils/ResultFormatters/TitleInfoFormatter.cs
  CompatBot/Utils/ResultFormatters/TitlePatchFormatter.cs
  PsnClient/PsnClient.cs
  PsnClient/PsnClient.csproj
Labels: bug

#183 The usual
  CompatBot/Config.cs
  CompatBot/EventHandlers/BotShutupHandler.cs
  CompatBot/EventHandlers/GithubLinksHandler.cs
  CompatBot/EventHandlers/IsTheGamePlayableHandler.cs
  CompatBot/EventHandlers/PostLogHelpHandler.cs
  CompatBot/Program.cs
  CompatBot/Utils/ResultFormatters/TitleInfoFormatter.cs
  CompatBot/Utils/RolesExtensions.cs
Labels: enhancement, fun stuff

#184 Use explain text for log uploading whenever possible
  CompatBot/EventHandlers/LogAsTextMonitor.cs
  CompatBot/EventHandlers/PostLogHelpHandler.cs
Labels: enhancement

#185 Update !rate command
  CompatBot/Commands/CompatList.cs
  CompatBot/Commands/Misc.cs
  CompatBot/Commands/Sudo.Mod.cs
  CompatBot/Utils/DiscordClientExtensions.cs
Labels: fun stuff

#186 I swear this is the last one [for today]
  CompatBot/Commands/Explain.cs
  CompatBot/Commands/Misc.cs
  CompatBot/Commands/Sudo.Mod.cs
  CompatBot/EventHandlers/IsTheGamePlayableHandler.cs
Labels: enhancement

#187 I lied. But memes are important
  CompatBot/Commands/Misc.cs
Labels: bug, fun stuff

#188 Misc enhancements
  CompatBot/Commands/CompatList.cs
  CompatBot/Config.cs
  CompatBot/EventHandlers/GithubLinksHandler.cs
  CompatBot/EventHandlers/IsTheGamePlayableHandler.cs
  CompatBot/EventHandlers/NewBuildsMonitor.cs
  CompatBot/EventHandlers/PostLogHelpHandler.cs
  CompatBot/Program.cs
Labels: enhancement

#189 Support fuzzy matches
  CompatBot/Commands/CompatList.cs
  CompatBot/Commands/Explain.cs
  CompatBot/Commands/Pr.cs
  CompatBot/CompatBot.csproj
  CompatBot/EventHandlers/IsTheGamePlayableHandler.cs
  CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
  CompatBot/EventHandlers/NewBuildsMonitor.cs
  CompatBot/EventHandlers/PostLogHelpHandler.cs
  CompatBot/Utils/CommandContextExtensions.cs
  CompatBot/Utils/CompatApiResultUtils.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
  CompatBot/Utils/StringUtils.cs
Labels: bug, enhancement, log analyzer

#190 Tweak explain fuzzy matching a little bit
  CompatBot/Commands/Explain.cs
  CompatBot/EventHandlers/IsTheGamePlayableHandler.cs
  CompatBot/EventHandlers/PostLogHelpHandler.cs
Labels: enhancement

#191 Various tweaks
  AppveyorClient/Client.cs
  AppveyorClient/POCOs/Build.cs
  CompatApiClient/POCOs/UpdateInfo.cs
  CompatBot/Commands/CompatList.cs
  CompatBot/EventHandlers/IsTheGamePlayableHandler.cs
  CompatBot/EventHandlers/PostLogHelpHandler.cs
  CompatBot/Utils/ResultFormatters/UpdateInfoFormatter.cs
  GithubClient/POCOs/PrInfo.cs
Labels: enhancement

#192 More interaction tweaks
  CompatBot/EventHandlers/BotShutupHandler.cs
  CompatBot/EventHandlers/IsTheGamePlayableHandler.cs
Labels: bug, fun stuff

#196 Misc updates
  CompatBot/Commands/E3.cs
  CompatBot/Commands/Warnings.cs
  CompatBot/Utils/DiscordClientExtensions.cs
Labels: bug, enhancement

#197 Fix PR build linking
  Clients/AppveyorClient/AppveyorClient.csproj
  Clients/AppveyorClient/Client.cs
  Clients/AppveyorClient/POCOs/Artifact.cs
  Clients/AppveyorClient/POCOs/ArtifactInfo.cs
  Clients/AppveyorClient/POCOs/Build.cs
  Clients/AppveyorClient/POCOs/BuildInfo.cs
  Clients/AppveyorClient/POCOs/HistoryInfo.cs
  Clients/AppveyorClient/POCOs/Job.cs
  Clients/AppveyorClient/POCOs/Project.cs
  Clients/CompatApiClient/ApiConfig.cs
  Clients/CompatApiClient/Client.cs
  Clients/CompatApiClient/CompatApiClient.csproj
  Clients/CompatApiClient/Compression/CompressedContent.cs
  Clients/CompatApiClient/Compression/CompressionMessageHandler.cs
  Clients/CompatApiClient/Compression/Compressor.cs
  Clients/CompatApiClient/Compression/DecompressedContent.cs
  Clients/CompatApiClient/Compression/DeflateCompressor.cs
  Clients/CompatApiClient/Compression/GZipCompressor.cs
  Clients/CompatApiClient/Compression/ICompressor.cs
  Clients/CompatApiClient/Formatters/JsonContractResolver.cs
  Clients/CompatApiClient/Formatters/NamingStyles.cs
  Clients/CompatApiClient/POCOs/CompatResult.cs
  Clients/CompatApiClient/POCOs/UpdateInfo.cs
  Clients/CompatApiClient/RequestBuilder.cs
  Clients/CompatApiClient/Utils/ConsoleLogger.cs
  Clients/CompatApiClient/Utils/UriExtensions.cs
  Clients/CompatApiClient/Utils/Utils.cs
  Clients/GithubClient/Client.cs
  Clients/GithubClient/GithubClient.csproj
  Clients/GithubClient/POCOs/PrInfo.cs
  Clients/GithubClient/POCOs/StatusInfo.cs
  Clients/IrdLibraryClient/IrdClient.cs
  Clients/IrdLibraryClient/IrdFormat/Ird.cs
  Clients/IrdLibraryClient/IrdFormat/IrdParser.cs
  Clients/IrdLibraryClient/IrdFormat/IsoHeaderParser.cs
  Clients/IrdLibraryClient/IrdLibraryClient.csproj
  Clients/IrdLibraryClient/POCOs/SearchResult.cs
  Clients/PsnClient/CustomTlsCertificatesHandler.cs
  Clients/PsnClient/POCOs/App.cs
  Clients/PsnClient/POCOs/Container.cs
  Clients/PsnClient/POCOs/Relationships.cs
  Clients/PsnClient/POCOs/StoreNavigation.cs
  Clients/PsnClient/POCOs/Stores.cs
  Clients/PsnClient/POCOs/TitleMeta.cs
  Clients/PsnClient/POCOs/TitlePatch.cs
  Clients/PsnClient/PsnClient.cs
  Clients/PsnClient/PsnClient.csproj
  Clients/PsnClient/Utils/LocaleUtils.cs
  Clients/PsnClient/Utils/TmdbHasher.cs
  CompatBot/Commands/Pr.cs
  CompatBot/CompatBot.csproj
  Tests/Tests.csproj
  discord-bot-net.sln
Labels: bug

#198 Various bugfixes
  CompatBot/Commands/Invites.cs
  CompatBot/Commands/Pr.cs
  CompatBot/EventHandlers/DiscordInviteFilter.cs
  CompatBot/EventHandlers/IsTheGamePlayableHandler.cs
  CompatBot/EventHandlers/LogParsingHandler.cs
Labels: bug
