Repository RPCS3/discord-bot, pull requests merged in 2020-03, with the labels that each got.

#525 Rewrite log parser to properly support multi-value items
  Clients/AppveyorClient/AppveyorClient.csproj
  Clients/GithubClient/GithubClient.csproj
  Clients/PsnClient/PsnClient.csproj
  CompatBot/CompatBot.csproj
  CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
  CompatBot/EventHandlers/LogParsing/LogParser.PipeReader.cs
  CompatBot/EventHandlers/LogParsing/LogParser.StateMachineGenerator.cs
  CompatBot/EventHandlers/LogParsing/POCOs/LogParseState.cs
  CompatBot/EventHandlers/UnknownCommandHandler.cs
  CompatBot/Utils/NameUniqueObjectCollection.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
  CompatBot/Utils/UniqueList.cs
Labels: log analyzer

#526 Update fatal error handling with the new multivalue system
  CompatBot/Database/Providers/SyscallInfoProvider.cs
  CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
Labels: bug, log analyzer

#527 Fix the syscall fix
  CompatBot/Database/Providers/SyscallInfoProvider.cs
Labels: bug

#528 Initial support for Linux PR builds
  CompatBot/Commands/BotStats.cs
  CompatBot/Commands/Pr.cs
  CompatBot/CompatBot.csproj
  CompatBot/Config.cs
  CompatBot/Database/Providers/SyscallInfoProvider.cs
Labels: enhancement

#529 Maintenance update
  Clients/GithubClient/POCOs/PrInfo.cs
  CompatBot/Commands/Pr.cs
  CompatBot/EventHandlers/LogParsing/ArchiveHandlers/PlainText.cs
  CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
  CompatBot/EventHandlers/UsernameZalgoMonitor.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.CurrentSettingsSections.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
Labels: bug, enhancement, log analyzer

#530 Add Azure Computer Vision services integration
  CompatBot/Commands/Attributes/RequiresSupporterRole.cs
  CompatBot/Commands/BotStats.cs
  CompatBot/Commands/Vision.cs
  CompatBot/CompatBot.csproj
  CompatBot/Config.cs
  CompatBot/Database/Providers/ContentFilter.cs
  CompatBot/EventHandlers/MediaScreenshotMonitor.cs
  CompatBot/Program.cs
  CompatBot/Utils/Extensions/RolesExtensions.cs
Labels: enhancement, fun stuff

#531 Add support for OneDrive log links
  Clients/AppveyorClient/Client.cs
  Clients/CompatApiClient/ApiConfig.cs
  Clients/CompatApiClient/Utils/UriExtensions.cs
  Clients/GithubClient/Client.cs
  Clients/OneDriveClient/Client.cs
  Clients/OneDriveClient/OneDriveClient.csproj
  Clients/OneDriveClient/POCOs/DriveItemMeta.cs
  CompatBot/Commands/BotStats.cs
  CompatBot/Commands/Vision.cs
  CompatBot/CompatBot.csproj
  CompatBot/Database/Providers/ContentFilter.cs
  CompatBot/EventHandlers/LogParsing/SourceHandlers/GenericLinkHandler.cs
  CompatBot/EventHandlers/LogParsing/SourceHandlers/GoogleDriveHandler.cs
  CompatBot/EventHandlers/LogParsing/SourceHandlers/OneDriveSourceHandler.cs
  CompatBot/EventHandlers/LogParsingHandler.cs
  CompatBot/EventHandlers/MediaScreenshotMonitor.cs
  CompatBot/Utils/Extensions/DiscordClientExtensions.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
  discord-bot-net.sln
Labels: enhancement, log analyzer

#532 Add support for FilterAction.ShowExplanation
  CompatBot/Commands/ContentFilters.cs
  CompatBot/Commands/Explain.cs
  CompatBot/Database/Providers/ContentFilter.cs
  CompatBot/EventHandlers/LogParsingHandler.cs
  CompatBot/Program.cs
Labels: enhancement

#533 Add an ability to set bot configuration dynamically
  CompatBot/Commands/Sudo.Bot.Configuration.cs
  CompatBot/Commands/Sudo.Bot.cs
  CompatBot/Config.cs
  CompatBot/Database/Providers/SqlConfiguration.cs
  CompatBot/Program.cs
Labels: enhancement

#534 Fix some issues with image description command
  CompatBot/Commands/Vision.cs
Labels: bug

#535 Some tweaks to the recent systems
  CompatBot/Commands/BotStats.cs
  CompatBot/Commands/Vision.cs
  CompatBot/EventHandlers/MediaScreenshotMonitor.cs
Labels: enhancement

#536 One weird trick
  CompatBot/Commands/Vision.cs
Labels: bug, fun stuff

#537 Fix wrong context for OCR checks
  CompatBot/EventHandlers/MediaScreenshotMonitor.cs
Labels: bug

#538 Minor tweaks
  CompatBot/Commands/Psn.cs
  CompatBot/EventHandlers/MediaScreenshotMonitor.cs
Labels: enhancement

#539 Make a separate channel list for OCR handler
  CompatBot/Config.cs
  CompatBot/EventHandlers/MediaScreenshotMonitor.cs
Labels: enhancement

#540 That's a wrong channel oops
  CompatBot/EventHandlers/MediaScreenshotMonitor.cs
Labels: bug, high priority

#541 I'll get it right one day
  CompatBot/EventHandlers/MediaScreenshotMonitor.cs
Labels: bug, high priority

#542 Misc update
  CompatBot/EventHandlers/MediaScreenshotMonitor.cs
  Tests/FlagTests.cs
Labels: enhancement

#543 Add new Nier patch note
  CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
Labels: log analyzer

#544 Fix check
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
  azure-pipelines.yml
Labels: bug, log analyzer

#545 Update some log checks
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
  azure-pipelines.yml
Labels: bug, log analyzer

#547 Maintenance
  Clients/CompatApiClient/CompatApiClient.csproj
  Clients/IrdLibraryClient/IrdLibraryClient.csproj
  Clients/PsnClient/PsnClient.csproj
  CompatBot/Commands/Sudo.Bot.cs
  CompatBot/Commands/Sudo.cs
  CompatBot/CompatBot.csproj
  CompatBot/Program.cs
  CompatBot/Watchdog.cs
  azure-pipelines.yml
Labels: enhancement

#550 Fix for fatal errors in older logs
  CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
Labels: log analyzer

#551 Misc updates
  CompatBot/EventHandlers/LogParsing/LogParser.PipeReader.cs
  CompatBot/EventHandlers/LogParsing/POCOs/LogParseState.cs
  CompatBot/EventHandlers/LogParsingHandler.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.WeirdSettingsSection.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
  CompatBot/Utils/UniqueList.cs
  Tests/RangeTests.cs
Labels: log analyzer

#552 Small fixes and tweaks
  CompatBot/Commands/Misc.cs
  CompatBot/EventHandlers/NewBuildsMonitor.cs
  CompatBot/EventHandlers/UnknownCommandHandler.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
  CompatBot/Utils/ResultFormatters/UpdateInfoFormatter.cs
Labels: bug, enhancement, log analyzer

#553 Fix the build monitor
  CompatBot/EventHandlers/NewBuildsMonitor.cs
Labels: bug

#554 Fix some log parsing performance issues
  CompatBot/Commands/Warnings.ListGroup.cs
  CompatBot/Database/Providers/ThumbnailProvider.cs
  CompatBot/EventHandlers/LogParsing/LogParser.LogSections.cs
  CompatBot/EventHandlers/LogParsing/LogParser.StateMachineGenerator.cs
  CompatBot/EventHandlers/LogParsing/POCOs/LogParseState.cs
  CompatBot/EventHandlers/LogParsingHandler.cs
  CompatBot/EventHandlers/NewBuildsMonitor.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.GeneralNotesSection.cs
  CompatBot/Utils/ResultFormatters/LogParserResultFormatter.cs
  Tests/LogParsingProfiler.cs
Labels: enhancement, log analyzer

#556 Update the bot after migration from AppVeyor to Azure DevOps
  Clients/AppveyorClient/AppveyorClient.csproj
  Clients/AppveyorClient/Client.cs
  Clients/AppveyorClient/POCOs/Artifact.cs
  Clients/AppveyorClient/POCOs/ArtifactInfo.cs
  Clients/AppveyorClient/POCOs/Build.cs
  Clients/AppveyorClient/POCOs/BuildInfo.cs
  Clients/AppveyorClient/POCOs/HistoryInfo.cs
  Clients/AppveyorClient/POCOs/Job.cs
  Clients/AppveyorClient/POCOs/Project.cs
  Clients/AppveyorClient/readme.md
  CompatBot/Commands/CompatList.cs
  CompatBot/Commands/Misc.cs
  CompatBot/Commands/Pr.cs
  CompatBot/CompatBot.csproj
  CompatBot/Config.cs
  CompatBot/EventHandlers/AppveyorLinksHandler.cs
  CompatBot/Program.cs
  CompatBot/Utils/Extensions/AzureDevOpsClientExtensions.cs
  CompatBot/Utils/ResultFormatters/UpdateInfoFormatter.cs
  Tests/LogParsingProfiler.cs
  discord-bot-net.sln
Labels: enhancement

#557 Minor fixes
  CompatBot/Commands/CompatList.cs
  CompatBot/Commands/Pr.cs
  CompatBot/Commands/Psn.Check.cs
Labels: bug

#559 Fix OCR filter
  CompatBot/EventHandlers/MediaScreenshotMonitor.cs
Labels: bug, high priority

#560 Maintenance
  CompatBot/Commands/Pr.cs
  CompatBot/EventHandlers/NewBuildsMonitor.cs
Labels: enhancement

#561 Announce new PS3 fw versions
  CompatBot/Commands/Psn.Check.cs
  CompatBot/Config.cs
  CompatBot/Program.cs
Labels: enhancement
